### ISSUE TITLE
[Arthan][Report] Graphical representation of baseline and endline data.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/arthan#34]
Refer this collection - https://reporting.openchs.org/collection/185
This collection has the required data in the tabular format.
 
Requirement Doc provided by Client-
[https://app.zenhub.com/files/208734466/ffcb0029-128b-4f60-b571-268febd21a6b/download](https://app.zenhub.com/files/208734466/ffcb0029-128b-4f60-b571-268febd21a6b/download) 

Graphical Requirement - 
https://docs.google.com/spreadsheets/d/1UuhjkPiBT3R9ITjTPGIWNhNK5wuwsTvbdTjPzzm3ciY/edit#gid=1098525559
For each given question client need to see graph in this format (given in the excel attached)

**Comment by vindeolal** [comment]
Created view ```arthan_indicators_view``` which can be used to plot different indicators.
