### ISSUE TITLE
Beneficiary Identification Form

### ISSUE THREAD

**Issue by arjunk** [avniproject/arthan#5]
Fields
- Student ID
- Date of birth

**Comment by garimadosar5** [comment]
QA Notes- 

- Student id does not show as mandatory but it does not search the case until student id is filled.
- If student id is not filled is give the error, "Unique record cannot be fetched". but there is only one record filled.

**Comment by arjunk** [comment]
@garimadosar5 Fixed point number 1. Also because of this point 2 won't be applicable. The other points to go platform related story.
