### ISSUE TITLE
[Arthan] Registration Related Reports.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/arthan#8]
https://docs.google.com/spreadsheets/d/1EGLehl_jzIxoklo6rENWRgFMp-ZGLE80gCcvWUdZsro/edit#gid=695855274

**Comment by garimadosar5** [comment]
QA Notes - 
- Student ID is not there in the filter.

**Comment by sachsk** [comment]
Created a new report for age-wise registration.
For the date filter issue created all the bar graphs again.
